## Basic Configuration

baseurl = "https://fidonode.me"
builddrafts = false
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Alex M"
title = "Alex M"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-50829185-2"
enableRobotsTXT = true

## Site Settings
[params]
author = "Alex Mihailov"
intro = "Full stack developer | FP-curious </br> Lambda affected | Wanna be rustacean 🦀"
description = "Now <a href='https://www.samsungnext.com/' target='_blank'>@Samsung NEXT</a> <a href='https://whisk.com/' target='_blank'>(Whisk product team)</a>. </br> Previously <a href='https://www.visualthreat.com/' target='_blank'>@VisualThreat</a>. </br> Work with: Scala, Mongo, MySQL, Thrift, gRPC"
resume = "resume.pdf"
authorimage = "ph.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Pretty own blog."
keywords = ""

## Social Accounts
[params.social]
github = "michey"
instagram = "aleksandr.mihailov"
#linkedin = "<username>"
twitter = "fido_node"
#facebook = "<username>"
#google = "<username>"
#stackoverflow = "<username>"
telegram = "fido_node"
email = "aleksandr.mihailov@pm.me"
twitch = "fido_node"

## Extras
[params.extra]
copyright = "© 2020. Aleksandr Mihailov. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
hightlightjs = true

## Main Menu
#[[menu.main]]
#    name = "blog"
#    weight = 100
#    identifier = "blog"
#    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"

[markup.goldmark.renderer]
unsafe= true