## Basic Configuration

baseurl = "https://michey.github.io"
builddrafts = false
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Alex M"
title = "Alex M"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-50829185-2"
enableRobotsTXT = true

## Site Settings
[params]
author = "Alex Mihailov"
intro = "Full stack developer | FP-curious | Lambda affected"
description = "Now @Whisk. Previously @VisualThreat. </br> Work with: Scala, React"
resume = "resume.pdf"
authorimage = "ph.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Pretty own blog."
keywords = ""

## Social Accounts
[params.social]
github = "michey"
instagram = "aleksandr.mihailov"
#linkedin = "<username>"
twitter = "fido_node"
#facebook = "<username>"
#google = "<username>"
#stackoverflow = "<username>"
telegram = "fido_node"
email = "aleksandr.mihailov@pm.me"
whatsapp = "79218951179"

## Extras
[params.extra]
copyright = "© 2018. Aleksandr Mihailov. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
hightlightjs = true

## Main Menu
#[[menu.main]]
#    name = "blog"
#    weight = 100
#    identifier = "blog"
#    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
